const strings = {
  LOGIN: 'Sign in',
  SIGNUP1: "Don't have an account ? ",
  SIGNUP2: 'Sign up.',
  LOGIN1: 'Already have an account ? ',
  LOGIN2: 'Sign in.',
  REGISTER: 'Sign up',
  LOGOUT: 'Log Out',
  WELCOME_TO_LOGIN: 'Login',
  WELCOME_TO_REGISTER: 'Register',
  WELCOME_TITLE_APP: 'Toon Kingdom',
  EMAIL_PLACEHOLDER: 'Email',
  PASSWORD_PLACEHOLDER: 'Password',
  TRYAGAIN: 'Try Again',
  MODALMSG: 'Sorry, something went wrong.',
  FONT: 'Muli-Regular',
  FONT_SEMIBOLD: 'Muli-SemiBold',
  FONT_BOLD: 'Muli-Bold',
  FONT_EXTRABOLD: 'Muli-ExtraBold',
  FONT_BLACK: 'Muli-Black',
  FAVORITES: 'Favorites',
  ALL: 'Webtoons',
  FORYOU: 'For You',
  MYFAV: 'My Favorite',
  PROFILE: 'My Profile',
  TRYAGAIN: 'Try Again',
  FAVWARN: "There's no bookmark yet.",
  LOADING: 'Loading, please wait ..',
  IMAGE1_URL: 'dummy',
  IMAGE2_URL: 'dummy',
  IMAGE3_URL: 'dummy',
  IMAGE4_URL: 'dummy',
  IMAGE5_URL: 'dummy',
  IMAGE6_URL: 'dummy',
  CREATE_TOON_PAGE: 'My Toon Kingdom',
  TITLE: 'Title',
  EPISODE: 'Episode',
  NAME: 'Name',
  IMAGES: 'Images',
  ADD_EPISODE: '+ Episode',
  ADD_IMAGE: '+ Image',
  DELETE: 'Delete',
  SEARCH: 'Search here ..',
  TYPE: 'Type here ..',
  LIKE: ' Favorite(s)',
  OVERVIEW: 'Overview',
  EPISODES: 'Episodes',
  READ: 'Read now',
};

export default strings;
